# Generated by Django 4.2.7 on 2024-01-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0002_remove_product_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='row_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
